server:
  port: 8762
spring:
  application:
    name: qis-eureka-server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  dashboard:
    enabled: true