server:
  port: 9006
#注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称： 192.168.1.103:lagou-service-resume:8080，我们可以自定义它
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
spring:
  application:
    name: qis-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ShuoQi/spring-cloud-service-config.git #配置git服务地址
          username: 18301029378 #配置git用户名
          password: qishuo5283589 #配置git密码
          default-label: main
          search-paths:
            - auth-code
            - email
            - gateway
            - user
      # 读取分支
      label: main
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
